# Backtest type definitions
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


# A single closed trade generated by the backtest engine
@dataclass
class BacktestTrade:
    entry_time: datetime
    exit_time: Optional[datetime]
    side: str
    entry_price: float
    exit_price: Optional[float]
    quantity: float
    pnl: float
    pnl_pct: float
    exit_reason: str
